import unittest
import sys, os
import json

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(os.path.join(os.path.dirname(__file__), '../..'))
from data_extractors import url_country_extractor


class TestUrlCountryExtractorMethods(unittest.TestCase):
    def setUp(self):
        file_path = os.path.join(os.path.dirname(__file__), "../ground_truth/url_countries.jl")
        self.f = open(file_path, 'r')
        self.country_code_dict = {"gw": "Guinea-Bissau", "gu": "Guam", "gt": "Guatemala",
                                  "gs": "South Georgia and the South Sandwich Islands", "gr": "Greece",
                                  "gq": "Equatorial Guinea", "gp": "Guadeloupe", "gy": "Guyana", "gg": "Guernsey",
                                  "gf": "French Guiana", "ge": "Georgia", "gd": "Grenada", "gb": "United Kingdom",
                                  "ga": "Gabon", "gn": "Guinea", "gm": "Gambia", "gl": "Greenland", "gi": "Gibraltar",
                                  "gh": "Ghana", "tz": "Tanzania", "tv": "Tuvalu", "tw": "Taiwan",
                                  "tt": "Trinidad and Tobago", "tr": "Turkey", "tn": "Tunisia", "to": "Tonga",
                                  "tl": "East Timor", "tm": "Turkmenistan", "tj": "Tajikistan", "tk": "Tokelau",
                                  "th": "Thailand", "tf": "French Southern Territories", "tg": "Togo", "td": "Chad",
                                  "tc": "Turks and Caicos Islands", "GW": "Guinea-Bissau", "GU": "Guam",
                                  "GT": "Guatemala", "GS": "South Georgia and the South Sandwich Islands",
                                  "GR": "Greece", "GQ": "Equatorial Guinea", "GP": "Guadeloupe", "mg": "Madagascar",
                                  "GY": "Guyana", "GG": "Guernsey", "GF": "French Guiana", "GE": "Georgia",
                                  "GD": "Grenada", "GB": "United Kingdom", "GA": "Gabon", "GN": "Guinea",
                                  "GM": "Gambia", "GL": "Greenland", "GI": "Gibraltar", "GH": "Ghana", "vu": "Vanuatu",
                                  "md": "Moldova", "mm": "Myanmar", "ml": "Mali", "zm": "Zambia", "za": "South Africa",
                                  "mh": "Marshall Islands", "zw": "Zimbabwe", "mu": "Mauritius", "mt": "Malta",
                                  "mf": "Saint Martin", "mw": "Malawi", "mv": "Maldives", "mq": "Martinique",
                                  "mp": "Northern Mariana Islands", "ZM": "Zambia", "ms": "Montserrat",
                                  "mr": "Mauritania", "ZA": "South Africa", "ZW": "Zimbabwe", "ME": "Montenegro",
                                  "MD": "Moldova", "MG": "Madagascar", "MF": "Saint Martin", "MA": "Morocco",
                                  "MC": "Monaco", "MM": "Myanmar", "ML": "Mali", "MO": "Macao", "MN": "Mongolia",
                                  "MH": "Marshall Islands", "MK": "Macedonia", "MU": "Mauritius", "MT": "Malta",
                                  "MW": "Malawi", "MV": "Maldives", "MQ": "Martinique",
                                  "MP": "Northern Mariana Islands", "MS": "Montserrat", "MR": "Mauritania",
                                  "mz": "Mozambique", "MY": "Malaysia", "MX": "Mexico", "MZ": "Mozambique",
                                  "FR": "France", "FI": "Finland", "FJ": "Fiji", "FK": "Falkland Islands",
                                  "FM": "Micronesia", "FO": "Faroe Islands", "me": "Montenegro", "SZ": "Swaziland",
                                  "SY": "Syria", "SX": "Sint Maarten", "ma": "Morocco", "mc": "Monaco",
                                  "SS": "South Sudan", "SR": "Suriname", "mo": "Macao", "mn": "Mongolia",
                                  "SV": "El Salvador", "mk": "Macedonia", "ST": "Sao Tome and Principe",
                                  "SK": "Slovakia", "SJ": "Svalbard and Jan Mayen", "SI": "Slovenia",
                                  "SH": "Saint Helena", "SO": "Somalia", "SN": "Senegal", "SM": "San Marino",
                                  "SL": "Sierra Leone", "SC": "Seychelles", "SB": "Solomon Islands",
                                  "SA": "Saudi Arabia", "SG": "Singapore", "mx": "Mexico", "SE": "Sweden",
                                  "SD": "Sudan", "YE": "Yemen", "YT": "Mayotte", "LB": "Lebanon", "LC": "Saint Lucia",
                                  "LA": "Laos", "LK": "Sri Lanka", "LI": "Liechtenstein", "LV": "Latvia",
                                  "LT": "Lithuania", "LU": "Luxembourg", "LR": "Liberia", "LS": "Lesotho",
                                  "LY": "Libya", "fr": "France", "fi": "Finland", "fj": "Fiji",
                                  "fk": "Falkland Islands", "fm": "Micronesia", "fo": "Faroe Islands",
                                  "sz": "Swaziland", "sy": "Syria", "sx": "Sint Maarten", "ss": "South Sudan",
                                  "sr": "Suriname", "sv": "El Salvador", "st": "Sao Tome and Principe",
                                  "sk": "Slovakia", "sj": "Svalbard and Jan Mayen", "si": "Slovenia",
                                  "sh": "Saint Helena", "so": "Somalia", "sn": "Senegal", "sm": "San Marino",
                                  "sl": "Sierra Leone", "sc": "Seychelles", "sb": "Solomon Islands",
                                  "sa": "Saudi Arabia", "sg": "Singapore", "se": "Sweden", "sd": "Sudan",
                                  "RU": "Russia", "RW": "Rwanda", "lb": "Lebanon", "lc": "Saint Lucia", "RS": "Serbia",
                                  "lk": "Sri Lanka", "li": "Liechtenstein", "lv": "Latvia", "RE": "Reunion",
                                  "lt": "Lithuania", "lu": "Luxembourg", "lr": "Liberia", "ls": "Lesotho",
                                  "RO": "Romania", "ly": "Libya", "ye": "Yemen", "yt": "Mayotte",
                                  "eh": "Western Sahara", "ee": "Estonia", "eg": "Egypt", "ec": "Ecuador",
                                  "et": "Ethiopia", "es": "Spain", "er": "Eritrea", "ru": "Russia", "rw": "Rwanda",
                                  "rs": "Serbia", "re": "Reunion", "ro": "Romania", "EH": "Western Sahara",
                                  "EE": "Estonia", "EG": "Egypt", "EC": "Ecuador", "ET": "Ethiopia", "ES": "Spain",
                                  "ER": "Eritrea", "VU": "Vanuatu", "xk": "Kosovo", "XK": "Kosovo", "KG": "Kyrgyzstan",
                                  "KE": "Kenya", "KI": "Kiribati", "KH": "Cambodia", "KN": "Saint Kitts and Nevis",
                                  "KM": "Comoros", "KR": "South Korea", "KP": "North Korea", "KW": "Kuwait",
                                  "KZ": "Kazakhstan", "KY": "Cayman Islands", "DO": "Dominican Republic",
                                  "DM": "Dominica", "DJ": "Djibouti", "DK": "Denmark", "DE": "Germany", "DZ": "Algeria",
                                  "my": "Malaysia", "kg": "Kyrgyzstan", "ke": "Kenya", "ki": "Kiribati",
                                  "kh": "Cambodia", "kn": "Saint Kitts and Nevis", "km": "Comoros", "QA": "Qatar",
                                  "kr": "South Korea", "kp": "North Korea", "kw": "Kuwait", "kz": "Kazakhstan",
                                  "ky": "Cayman Islands", "WF": "Wallis and Futuna", "JP": "Japan", "JM": "Jamaica",
                                  "JO": "Jordan", "WS": "Samoa", "JE": "Jersey", "do": "Dominican Republic",
                                  "dm": "Dominica", "dj": "Djibouti", "dk": "Denmark", "de": "Germany", "dz": "Algeria",
                                  "qa": "Qatar", "PR": "Puerto Rico", "PS": "Palestinian Territory", "PW": "Palau",
                                  "PT": "Portugal", "PY": "Paraguay", "PA": "Panama", "PF": "French Polynesia",
                                  "PG": "Papua New Guinea", "PE": "Peru", "PK": "Pakistan", "PH": "Philippines",
                                  "PN": "Pitcairn", "PL": "Poland", "PM": "Saint Pierre and Miquelon",
                                  "wf": "Wallis and Futuna", "jp": "Japan", "jm": "Jamaica", "jo": "Jordan",
                                  "ws": "Samoa", "je": "Jersey", "la": "Laos", "ck": "Cook Islands",
                                  "ci": "Ivory Coast", "ch": "Switzerland", "co": "Colombia", "cn": "China",
                                  "cm": "Cameroon", "cl": "Chile", "cc": "Cocos Islands", "ca": "Canada",
                                  "cg": "Republic of the Congo", "cf": "Central African Republic",
                                  "cd": "Democratic Republic of the Congo", "cz": "Czechia", "cy": "Cyprus",
                                  "cx": "Christmas Island", "cs": "Serbia and Montenegro", "cr": "Costa Rica",
                                  "cw": "Curacao", "cv": "Cape Verde", "cu": "Cuba", "pr": "Puerto Rico",
                                  "ps": "Palestinian Territory", "pw": "Palau", "pt": "Portugal", "py": "Paraguay",
                                  "pa": "Panama", "pf": "French Polynesia", "pg": "Papua New Guinea", "pe": "Peru",
                                  "pk": "Pakistan", "ph": "Philippines", "pn": "Pitcairn", "pl": "Poland",
                                  "pm": "Saint Pierre and Miquelon", "CK": "Cook Islands", "CI": "Ivory Coast",
                                  "CH": "Switzerland", "CO": "Colombia", "CN": "China", "CM": "Cameroon", "CL": "Chile",
                                  "CC": "Cocos Islands", "CA": "Canada", "CG": "Republic of the Congo",
                                  "CF": "Central African Republic", "CD": "Democratic Republic of the Congo",
                                  "CZ": "Czechia", "CY": "Cyprus", "CX": "Christmas Island",
                                  "CS": "Serbia and Montenegro", "CR": "Costa Rica", "CW": "Curacao",
                                  "CV": "Cape Verde", "CU": "Cuba", "va": "Vatican",
                                  "vc": "Saint Vincent and the Grenadines", "ve": "Venezuela",
                                  "vg": "British Virgin Islands", "iq": "Iraq", "vi": "U.S. Virgin Islands",
                                  "is": "Iceland", "ir": "Iran", "it": "Italy", "vn": "Vietnam", "im": "Isle of Man",
                                  "il": "Israel", "io": "British Indian Ocean Territory", "in": "India",
                                  "ie": "Ireland", "id": "Indonesia", "VA": "Vatican",
                                  "VC": "Saint Vincent and the Grenadines", "VE": "Venezuela",
                                  "VG": "British Virgin Islands", "IQ": "Iraq", "VI": "U.S. Virgin Islands",
                                  "IS": "Iceland", "IR": "Iran", "IT": "Italy", "VN": "Vietnam", "IM": "Isle of Man",
                                  "IL": "Israel", "IO": "British Indian Ocean Territory", "IN": "India",
                                  "nl": "Netherlands", "IE": "Ireland", "ID": "Indonesia", "BD": "Bangladesh",
                                  "BE": "Belgium", "BF": "Burkina Faso", "BG": "Bulgaria",
                                  "BA": "Bosnia and Herzegovina", "BB": "Barbados", "BL": "Saint Barthelemy",
                                  "BM": "Bermuda", "BN": "Brunei", "BO": "Bolivia", "BH": "Bahrain", "BI": "Burundi",
                                  "BJ": "Benin", "BT": "Bhutan", "BV": "Bouvet Island", "BW": "Botswana",
                                  "BQ": "Bonaire, Saint Eustatius and Saba ", "BR": "Brazil", "BS": "Bahamas",
                                  "BY": "Belarus", "BZ": "Belize", "nz": "New Zealand", "np": "Nepal", "nr": "Nauru",
                                  "OM": "Oman", "nu": "Niue", "HR": "Croatia", "HT": "Haiti", "HU": "Hungary",
                                  "HK": "Hong Kong", "HN": "Honduras", "HM": "Heard Island and McDonald Islands",
                                  "bd": "Bangladesh", "be": "Belgium", "bf": "Burkina Faso", "bg": "Bulgaria",
                                  "ba": "Bosnia and Herzegovina", "bb": "Barbados", "bl": "Saint Barthelemy",
                                  "bm": "Bermuda", "bn": "Brunei", "bo": "Bolivia", "bh": "Bahrain", "bi": "Burundi",
                                  "bj": "Benin", "bt": "Bhutan", "bv": "Bouvet Island", "bw": "Botswana",
                                  "bq": "Bonaire, Saint Eustatius and Saba ", "br": "Brazil", "bs": "Bahamas",
                                  "by": "Belarus", "bz": "Belize", "om": "Oman", "UY": "Uruguay", "UZ": "Uzbekistan",
                                  "US": "United States", "UM": "United States Minor Outlying Islands", "UG": "Uganda",
                                  "UA": "Ukraine", "NI": "Nicaragua", "NL": "Netherlands", "NO": "Norway",
                                  "NC": "New Caledonia", "NE": "Niger", "NF": "Norfolk Island", "NG": "Nigeria",
                                  "NZ": "New Zealand", "NP": "Nepal", "NR": "Nauru", "NU": "Niue", "hr": "Croatia",
                                  "ht": "Haiti", "hu": "Hungary", "hk": "Hong Kong", "hn": "Honduras",
                                  "hm": "Heard Island and McDonald Islands", "uy": "Uruguay", "uz": "Uzbekistan",
                                  "us": "United States", "um": "United States Minor Outlying Islands", "ug": "Uganda",
                                  "ua": "Ukraine", "ae": "United Arab Emirates", "ad": "Andorra",
                                  "ag": "Antigua and Barbuda", "af": "Afghanistan", "ai": "Anguilla", "am": "Armenia",
                                  "al": "Albania", "ao": "Angola", "an": "Netherlands Antilles", "aq": "Antarctica",
                                  "as": "American Samoa", "ar": "Argentina", "au": "Australia", "at": "Austria",
                                  "aw": "Aruba", "ax": "Aland Islands", "az": "Azerbaijan", "ni": "Nicaragua",
                                  "TZ": "Tanzania", "no": "Norway", "TV": "Tuvalu", "TW": "Taiwan",
                                  "TT": "Trinidad and Tobago", "nc": "New Caledonia", "nan": "Namibia", "ne": "Niger",
                                  "nf": "Norfolk Island", "ng": "Nigeria", "TN": "Tunisia", "TO": "Tonga",
                                  "TL": "East Timor", "TM": "Turkmenistan", "TJ": "Tajikistan", "TK": "Tokelau",
                                  "TH": "Thailand", "TF": "French Southern Territories", "TG": "Togo", "TD": "Chad",
                                  "TC": "Turks and Caicos Islands", "AE": "United Arab Emirates", "AD": "Andorra",
                                  "AG": "Antigua and Barbuda", "AF": "Afghanistan", "AI": "Anguilla", "AM": "Armenia",
                                  "AL": "Albania", "AO": "Angola", "AN": "Netherlands Antilles", "AQ": "Antarctica",
                                  "AS": "American Samoa", "AR": "Argentina", "AU": "Australia", "AT": "Austria",
                                  "AW": "Aruba", "AX": "Aland Islands", "AZ": "Azerbaijan", "TR": "Turkey",
                                  "fx": "France", "na": "Namibia", "nt": "Neutral Zone", "su": "Former USSR",
                                  "tp": "East Timor", "uk": "United Kingdom", "yu": "Yugoslavia", "zr": "Zaire",
                                  "usa": "United States"}

    def tearDown(self):
        pass

    def test_url_country_extractor(self):
        for line in self.f:
            x = json.loads(line)
            extraction = url_country_extractor.extract(x['tokens_url'], self.country_code_dict)
            self.assertEqual(x['expected'], extraction[0]['value'])

if __name__ == '__main__':
    unittest.main()
