# -*- coding: utf-8 -*-
import unittest
import codecs
import os
import sys
import json

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(os.path.join(os.path.dirname(__file__), '../..'))
from data_extractors import link_extractor


class TestUrlExtractorMethods(unittest.TestCase):
    def setUp(self):
        file_path = os.path.join(os.path.dirname(__file__), "../ground_truth/szeke.jl")
        self.doc = json.load(codecs.open(file_path, 'r'))

    def tearDown(self):
        pass

    def test_url_extractor(self):
        extracted_links = link_extractor.extract_links(self.doc['html'], self.doc['url'])
        expected_links = [
            {'value': 'http://usc-isi-i2.github.io#home', 'metadata': {'text': 'Pedro Szekely', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io#home', 'metadata': {'text': 'Home', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io#about', 'metadata': {'text': 'About', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io#tweets', 'metadata': {'text': 'Tweets', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io#students', 'metadata': {'text': 'Students', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io#projects', 'metadata': {'text': 'Projects', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io#pub', 'metadata': {'text': 'Publications', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io#contact', 'metadata': {'text': 'Contact', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../', 'metadata': {'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/logo/iig-logo.png', 'metadata': {'type': 'image'}},
            {'value': 'http://www.isi.edu', 'metadata': {'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/logo/isi-logo.png', 'metadata': {'type': 'image'}},
            {'value': 'http://www.usc.edu', 'metadata': {'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/logo/usc-shield-name-white.png',
             'metadata': {'type': 'image'}},
            {'value': 'http://usc-isi-i2.github.io#about', 'metadata': {'type': 'href'}},
            {'value': 'https://www.linkedin.com/pub/pedro-szekely/2/a16/671', 'metadata': {'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/social/linkedin.jpg', 'metadata': {'type': 'image'}},
            {'value': 'https://twitter.com/szeke', 'metadata': {'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/social/twitter.jpg', 'metadata': {'type': 'image'}},
            {'value': 'http://www.researchgate.net/profile/Pedro_Szekely', 'metadata': {'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/social/rg.jpg', 'metadata': {'type': 'image'}},
            {'value': 'http://scholar.google.com/citations?user=U1A6iBMAAAAJ&hl=en', 'metadata': {'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/social/google-scholar.png', 'metadata': {'type': 'image'}},
            {'value': 'http://www.slideshare.net/szeke/presentations', 'metadata': {'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/social/slideshare.jpg', 'metadata': {'type': 'image'}},
            {'value': 'http://usc-isi-i2.github.io/doc/szekely-cv.pdf', 'metadata': {'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/social/cv.png', 'metadata': {'type': 'image'}},
            {'value': 'http://usc-isi-i2.github.io#pub', 'metadata': {'text': 'this page', 'type': 'href'}},
            {'value': 'http://scholar.google.com/citations?user=U1A6iBMAAAAJ&hl=en',
             'metadata': {'text': 'Google Scholar', 'type': 'href'}},
            {'value': 'http://www.researchgate.net/profile/Pedro_Szekely/',
             'metadata': {'text': 'Research Gate', 'type': 'href'}},
            {'value': 'https://www.youtube.com/playlist?list=PLdD4tO6i0DwMXmBhOwlt7zEZKoOWrWpOA',
             'metadata': {'text': 'YouTube', 'type': 'href'}},
            {'value': 'http://www.slideshare.net/szeke/presentations',
             'metadata': {'text': 'Slideshare', 'type': 'href'}},
            {'value': 'http://pedroszekely.blogspot.com', 'metadata': {'text': 'blog', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../karma', 'metadata': {'text': 'Karma page', 'type': 'href'}},
            {'value': 'http://www.linkedin.com/pub/pedro-szekely/2/a16/671',
             'metadata': {'text': 'LinkedIn', 'type': 'href'}},
            {'value': 'https://www.facebook.com/pedro.szekely', 'metadata': {'text': 'Facebook', 'type': 'href'}},
            {'value': 'https://twitter.com/szeke', 'metadata': {'text': 'Twitter', 'type': 'href'}},
            {'value': 'http://www.flickr.com/photos/pedrosz', 'metadata': {'text': 'Flickr', 'type': 'href'}},
            {'value': 'https://plus.google.com/112114906025524678483', 'metadata': {'text': 'Google+', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io#students', 'metadata': {'text': 'here', 'type': 'href'}},
            {'value': 'http://americanart.si.edu',
             'metadata': {'text': 'Smithsonian American Art Museum', 'type': 'href'}},
            {'value': 'http://www.isi.edu/integration/people/knoblock/index.html',
             'metadata': {'text': 'Information Integration Group', 'type': 'href'}},
            {'value': 'http://www.isi.edu/~ambite/', 'metadata': {'text': 'Jose Luis Ambite', 'type': 'href'}},
            {'value': 'http://www.isi.edu/people/burns/homepage', 'metadata': {'text': 'Gully Burns', 'type': 'href'}},
            {'value': 'http://www.isi.edu/~gil/', 'metadata': {'text': 'Yolanda Gil', 'type': 'href'}},
            {'value': 'http://www.yoyoi.info/', 'metadata': {'text': 'Yao-Yi Chiang', 'type': 'href'}},
            {'value': 'http://www.isi.edu/people/maheswar/contact',
             'metadata': {'text': 'Rajiv Maheswaran', 'type': 'href'}},
            {'value': 'http://www.isi.edu/people/ychang/', 'metadata': {'text': 'Yu-Han Chang', 'type': 'href'}},
            {'value': 'http://www.aifb.kit.edu/web/Rudi_Studer/en',
             'metadata': {'text': 'Rudi Studer', 'type': 'href'}},
            {'value': 'http://harth.org/andreas/', 'metadata': {'text': 'Andreas Harth', 'type': 'href'}},
            {'value': 'http://www.aifb.kit.edu/web/Steffen_Stadtm%C3%BCller/en',
             'metadata': {'text': u'Steffen Stadtm\xfcller', 'type': 'href'}},
            {'value': 'http://mayor2.dia.fi.upm.es/oeg-upm/index.php/es/phdstudents/50-fpriyatna/',
             'metadata': {'text': 'Freddy Priyatna', 'type': 'href'}},
            {'value': 'http://www.linkedin.com/in/aviggio', 'metadata': {'text': 'Alex Viggio', 'type': 'href'}},
            {'value': 'http://vivoweb.org/', 'metadata': {'text': 'VIVO', 'type': 'href'}}, {
                'value': 'http://americanart.si.edu/visit/contact/search/staffsearch.cfm?lastname=Allen&firstname=Rachel%20M.&format=long',
                'metadata': {'text': 'Rachel Allen', 'type': 'href'}},
            {'value': 'http://www.linkedin.com/pub/joan-cobb/a/799/648',
             'metadata': {'text': 'Joan Cobb', 'type': 'href'}},
            {'value': 'http://be.linkedin.com/pub/miel-vander-sande/36/702/410',
             'metadata': {'text': 'Miel Vander Sande', 'type': 'href'}},
            {'value': 'http://ceur-ws.org/Vol-914/paper_10.pdf',
             'metadata': {'text': 'everythingisconnected', 'type': 'href'}},
            {'value': 'http://www.uniandes.edu.co/', 'metadata': {'text': 'Universidad de los Andes', 'type': 'href'}},
            {'value': 'http://puj-portal.javeriana.edu.co/',
             'metadata': {'text': 'Pontificia Universidad Javeriana', 'type': 'href'}},
            {'value': 'http://boris.villazon.terrazas.name/',
             'metadata': {'text': 'Boris Villazon-Terrazas', 'type': 'href'}},
            {'value': 'https://twitter.com/szeke', 'metadata': {'text': 'Tweets by @szeke', 'type': 'href'}},
            {'value': 'http://bit.ly/18KLPBo', 'metadata': {'text': 'calendar', 'type': 'href'}}, {
                'value': 'https://maps.google.com/maps?f=d&source=s_d&saddr=&daddr=34.02001,-118.289902&hl=en&geocode=&sll=34.020021,-118.289983&sspn=0.002214,0.00284&vpsrc=0&mra=mift&mrsp=1&sz=19&ie=UTF8&t=m&z=19&iwloc=ddw1',
                'metadata': {'text': 'here', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../dig', 'metadata': {'text': '\n\t\t\t\t', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../karma', 'metadata': {'text': '\n\t\t\t\t', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../lodstories', 'metadata': {'text': '\n\t\t\t\t', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../semantic-modeling',
             'metadata': {'text': '\n\t\t\t\t', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../wtnic-project',
             'metadata': {'text': '\n\t\t\t\t', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../princess', 'metadata': {'text': '\n\t\t\t\t', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../scharp', 'metadata': {'text': '\n\t\t\t\t', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../effect', 'metadata': {'text': '\n\t\t\t\t', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../aac', 'metadata': {'text': '\n\t\t\t\t', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../thor', 'metadata': {'text': '\n\t\t\t\t', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/projects/data-preparation.png',
             'metadata': {'type': 'image'}},
            {'value': 'http://www.wings-workflows.org/', 'metadata': {'text': 'WINGS', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/gil11-iswc.pdf',
             'metadata': {'text': "ISWC'2011", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/slides/tharmon11-IN51C1605-poster.pdf',
             'metadata': {'text': "AGU'2011", 'type': 'href'}},
            {'value': 'http://www.isi.edu/integration/people/knoblock/index.html',
             'metadata': {'text': 'Craig Knoblock', 'type': 'href'}},
            {'value': 'http://www.isi.edu/~gil/', 'metadata': {'text': 'Yolanda Gil', 'type': 'href'}},
            {'value': 'http://www.ucmerced.edu/content/thomas-c-harmon',
             'metadata': {'text': 'Tom Harmon', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/projects/gambit.png', 'metadata': {'type': 'image'}},
            {'value': 'http://www.isi.edu/integration/people/knoblock/index.html',
             'metadata': {'text': 'Craig Knoblock', 'type': 'href'}},
            {'value': 'http://www.isi.edu/people/ychang/', 'metadata': {'text': 'Yu-Han Chang', 'type': 'href'}},
            {'value': 'http://www.isi.edu/people/maheswar/contact',
             'metadata': {'text': 'Rajiv Maheswaran', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/projects/Enriching-Sensor-Data.png',
             'metadata': {'type': 'image'}}, {'value': 'http://gamepipe.usc.edu/USC_GamePipe_Laboratory/Home.html',
                                              'metadata': {'text': 'Cosmopolis', 'type': 'href'}},
            {'value': 'http://www.isi.edu/integration/people/knoblock/index.html',
             'metadata': {'text': 'Craig Knoblock', 'type': 'href'}},
            {'value': 'http://gamepipe.usc.edu/~zyda', 'metadata': {'text': 'Mike Zyda', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/projects/COMPASS.png', 'metadata': {'type': 'image'}},
            {'value': 'http://youtu.be/vmT86VXTN9Y', 'metadata': {'text': 'COMPASS features', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../papers/szekely2012-iui.pdf',
             'metadata': {'text': "IUI'2012", 'type': 'href'}}, {'value': 'http://www.isi.edu/people/maheswar/contact',
                                                                 'metadata': {'text': 'Rajiv Maheswaran',
                                                                              'type': 'href'}},
            {'value': 'http://www.isi.edu/people/ychang/', 'metadata': {'text': 'Yu-Han Chang', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/projects/VizScript.png', 'metadata': {'type': 'image'}},
            {'value': 'http://usc-isi-i2.github.io/papers/jing08-iui.pdf',
             'metadata': {'text': "IUI'2008a", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/rsanchez08-iui.pdf',
             'metadata': {'text': "IUI'2008b", 'type': 'href'}}, {'value': 'http://www.isi.edu/people/maheswar/contact',
                                                                  'metadata': {'text': 'Rajiv Maheswaran',
                                                                               'type': 'href'}},
            {'value': 'http://yalma.fime.uanl.mx/~romeo/', 'metadata': {'text': 'Romeo Sanchez', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/projects/VizPattern.png', 'metadata': {'type': 'image'}},
            {'value': 'http://www.youtube.com/watch?v=T5EcQItuJqM', 'metadata': {'text': 'Movie', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/jing09-vlhcc.pdf',
             'metadata': {'text': "VL/HCC'2009", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/jing10-vast.pdf',
             'metadata': {'text': "VAST'2010", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/projects/Living-Classroom.png',
             'metadata': {'type': 'image'}},
            {'value': 'http://usc-isi-i2.github.io/../img/projects/CSC.png', 'metadata': {'type': 'image'}},
            {'value': 'http://www.youtube.com/watch?v=kpkrP5RlAVQ',
             'metadata': {'text': 'AAMAS/ICAPS 2010 demo', 'type': 'href'}},
            {'value': 'https://youtu.be/5iufYM_O84g', 'metadata': {'text': 'system', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/szekely05-icaps.pdf',
             'metadata': {'text': "ICAPS'2005 (wkshp)", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/szekely06-ss0604.pdf',
             'metadata': {'text': "AAAI SS'2006", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/szekely06-aamas.pdf',
             'metadata': {'text': "AAMAS'2006", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/maheswar06-msdm.pdf',
             'metadata': {'text': "AAMAS MSDM'2006", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/maheswar06-lsmas.pdf',
             'metadata': {'text': "AAMAS LSMAS'2006", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/tharbers07-aaai.pdf',
             'metadata': {'text': "AAAI'2007", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/maheswar08-aamas.pdf',
             'metadata': {'text': "AAMAS'2008", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/maheswar08-icaps.pdf',
             'metadata': {'text': "ICAPS'2008", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/maheswar09-aamas.pdf',
             'metadata': {'text': "AAMAS'2009", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/maheswar10-psuu.pdf',
             'metadata': {'text': "ICAPS PSUU'2010", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/maheswar10-optmas.pdf',
             'metadata': {'text': "AAMAS OPTMAS'2010", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/maheswar10-aamasdemo.pdf',
             'metadata': {'text': "AAMAS'2010", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/maheswar10-arde.pdf',
             'metadata': {'text': "AAMAS ARDE'2010", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/maheswar11-prima.pdf',
             'metadata': {'text': "PRIMA'2011", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/projects/LANdroids.png', 'metadata': {'type': 'image'}},
            {'value': 'http://usc-isi-i2.github.io/papers/harris09-iros.pdf',
             'metadata': {'text': "IROS'2009", 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/projects/Commander.png', 'metadata': {'type': 'image'}},
            {'value': 'http://usc-isi-i2.github.io/../img/projects/SNAP.png', 'metadata': {'type': 'image'}},
            {'value': 'http://usc-isi-i2.github.io/slides/szekely02-snap-slides.pdf',
             'metadata': {'text': 'help operators', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/papers/rneches04-camera.pdf',
             'metadata': {'text': 'Final Report to DARPA', 'type': 'href'}},
            {'value': 'http://www.isi.edu/camera/', 'metadata': {'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/../img/projects/DEALMAKER.png', 'metadata': {'type': 'image'}},
            {'value': 'http://usc-isi-i2.github.io/papers/szekely99-dealmaker.pdf',
             'metadata': {'text': 'Project final documentation', 'type': 'href'}},
            {'value': 'http://usc-isi-i2.github.io/publications.html',
             'metadata': {'text': 'All Publications', 'type': 'href'}},
            {'value': 'mailto:pszekely@isi.edu', 'metadata': {'text': 'pszekely@isi.edu', 'type': 'href'}},
            {'value': 'tel:+1-310-448-8641', 'metadata': {'text': '+1 310 448 8641', 'type': 'href'}},
            {'value': 'http://bit.ly/18KLPBo', 'metadata': {'text': 'Appointment Times', 'type': 'href'}}]
        self.assertEqual(extracted_links, expected_links)

if __name__ == '__main__':
    unittest.main()
