{"text": "? AVENUE SPA is celebrating its GRAND REOPENING ? We are one blocks south of 401/ Avenue Road ? Everything is top notch including our attendants ? Today (Wednesday) we have a very pretty new girl busty young Eva ? She has good reviews on TERB ? Please give her a warm welcome ? No Rushing or Upselling ? Showers In Spa ? Avenue Spa ? 2072 Avenue Road (south of 401/ Avenue Rd ) ? M5M 4A6 ? (416) 932-3720 The Top Asian Massage Experience of 2014", "extracted": [], "correct": ""}
{"text": "Delhi Escort in Jiya Kapoor From South Avenue 09899011054 Delhi Escort in Jiya Kapoor From South Avenue 09899011054", "extracted": [], "correct": ""}
{"text": "Do you live or work near Avenue Road? Visit Avenue Spa for a enjoyable massage. This week we have three ladies each day. Lisa is on shift Friday and Saturday. She is young and very pretty. We specialize is great massage without any rushing or upselling. Excellent place for prostate massage 30 minute massage is $40 Avenue Spa 2072 Avenue Road South of 401 and Wilson North York M5M 4A4 (416) 932-3720", "extracted": [], "correct": ""}
{"text": "647-313-8564 HOT VIDEO Asian escort Toronto, Don Mills/Sheppard SUPERB service in Ulta clean cozy location. This girl is amazing and will rock your world! Special skills that we dare not mention her boys. Pictures takes summer 2015. Video taken Jan. 2016 **************************Real Pictures Guarrantee ************ No No No No RUSH!!! Sheppard Avenue East, Toronto, ON M2J 5A7Sheppard Avenue East, Toronto, ON M2J 5A7", "extracted": [], "correct": ""}
{"text": "Elite Day Spa 2437 Alvin Avenue San Jose, CA 95121 (408) 509-8318 Join us for our Grand Opening ! Relaxation & spa treatment Elite Day Spa is San Jose's premier Day Spa & relaxation spot. Visit us today for an unforgettable session. Elite Day Spa 2437 Alvin Avenue San Jose, CA 95121 (408) 509-8318", "extracted": [], "correct": ""}
{"text": "Hey, my name is Maria and I am a sexy & VERY * BUSTY * 36DD (yes, they are big and natural!)Puerto Rican/Dominican Spanish Latina ready 4 u NOW. I have a soft, juicy booty! Fetish friendly... *100% Real Pics* 50 SPECIAL! 80/half 150/hr *OUTCALL MUST BE AT LEAST ONE HR* Call/Text MARIA 24/7 @ (646) 547-6683 NO Blocked Calls Sheepshead Bay - Avenue X (Near Nostrand Avenue ) Incall/Outcall Sheepshead, Marine Park, Midwood, Bensonhurst, Bay Ridge, Sunset Park, Park Slope", "extracted": [], "correct": ""}
{"text": "1959 GRAND AVENUE 858-886-7727 ?Asian relaxation at its best. Let us get those kinks out and get your blood flowing We love our customers to leave with a smile. br ?? TEL 858-886-7727 ?? OPEN 9am - 10pm ---?-----?-----?--- ? visit us today ? 1959 Grand avenue , Pacific Beach. Highway 5 Del Mar, La Jolla, Mission & Ocean Beach, Airport, Convention, Downtown.", "extracted": [], "correct": ""}
{"text": "? Enjoy Quality Time With a Gorgeous Provider Visit Massage Avenue !! - 23", "extracted": [], "correct": ""}
{"text": "http://www.royalmodel.in Call 08420771150 Central Avenue Royal escorts : Sexy Call girls services in Central Avenue : Call 08420771150 Central Avenue Royal escorts : Sexy Call girls services in Central Avenue : Call 08420771150 Central Avenue Royal escorts : Sexy Call girls services in Central Avenue : Call 08420771150 Central Avenue Royal escorts : Sexy Call girls services in Central Avenue : Call 08420771150 Central Avenue Royal escorts : Sexy Call girls services in Central Avenue : Call 08420771150 Central Avenue Royal escorts : Sexy Call girls services in Central Avenue : Call 08420771150 Central Avenue Royal escorts : Sexy Call girls services in Central Avenue : Call 08420771150 Central Avenue Royal escorts : Sexy Call girls services in Central Avenue : Call 08420771150 Contact Me to get Royal Model Escorts Appointment Request here for Pics Whatsapp: +91-8420771150 For more information & want quickest response from me then CAll +91-8420771150 http://www.royalmodel.in", "extracted": [], "correct": ""}
{"text": "Jade is back ??? incall only $80 queens blvd /Woodhaven blvd / junction blvd - 24", "extracted": [], "correct": ""}
{"text": "High quality massage services, Experience our clean and comfortable facilities, Best Body rubs in town! Shower Available & Private Room * ??$45 - Hour & 4 hands $80 only cash ??Address: 43-17 2fl Bell Blvd , Bayside.NY 11361 Direction- 495 Exit 26 & Norther Blvd ??Tel:718-224-2666?? Poster's age: 25 Location: , Bell Blvd / Northern Blvd , Baysid, Queens Post ID: 42805841 queens", "extracted": [], "correct": ""}
{"text": "???? Grand Open ??? ?? --??Northern Blvd ???Bell Blvd ??? Sweet ??? Enjoy with 100% young and real de? Japanese Style Bodyslide Spa ? 4 hands available ? Open 24hr / 7 days ? Get a very pleasurable massage at our safe in our location ? Definitely far from the usual... ? So DON'T HESITATE.. Call now & spend some quality time with US! ? Let us help you get rid of your stress ? Call us at ? Walk-ins Welcome!! ? ? Northern Blvd , Bell blvd , Bayside,al.", "extracted": [], "correct": ""}
{"text": "H Massage $40/Hr/ Private Room Boutique massage shop looking to provide a great massage at a reasonable price. Whether on vacation or just de-stressing after a long day, let us take care of your needs. We offer a variety of modalities and add on treatments. Many experienced and licensed therapists and intuitive healers. Walk ins welcome, call to insure no wait. 619-483-8661 619-825-3409 6784 El Cajon Blvd , 92115 --------7364 el cajon blvd ca 92115------5837 el cajon blvd ca 92115------------------------ 1012 grand ave ca 92109-------", "extracted": [], "correct": ""}
{"text": "NEW in town (LAX airport) 405fy Century blvd & la cienaga blvd MoTeL 6 young CaUcAsIaN 760 338 9043 21", "extracted": [], "correct": ""}
{"text": "???? Grand Open ??? ?? --??Northern Blvd ???Bell Blvd ??? Sweet ??? Enjoy with 100% young and real de? Japanese Style Bodyslide Spa ? 4 hands available ? Open 24hr / 7 days ? ? Let us help you get rid of your stress ? Call us at ? 917-517-7895 ? Walk-ins Welcome!! ? it's time to experience the royal treatment ? Northern Blvd , Bell blvd , Bayside,al.", "extracted": [], "correct": ""}
{"text": "Very passable black 25 year young TS girl with the best of the best! 9193959158 hosting off Western Boulevard NCstate area I'm waiting! 20-40 $pecial$", "extracted": [], "correct": ""}
{"text": "HOT EXOTIC SEXY MODELS IN THE 149 and southern boulevard area - 19", "extracted": [], "correct": ""}
{"text": "Brand New hot EXOTIC near149 and southern boulevard area - 19", "extracted": [], "correct": ""}
{"text": "Cuddle Bunny 704-977-8561real pics North Charlotte/University Area/IKEA Boulevard /University City Boulevard .", "extracted": [], "correct": ""}
{"text": "WE offer a selection of young beautiful latinas that are replaced weekly, from all over latin america.100% latin. Clean safe very discrete location. INCALL ONLY.. Call now 646 918 0821 or 347 272 9171 WE ARE CENTRALIZED BETWEEN LIC, RIDGEWOOD, WOODSIDE AND MASPETH NEAR QUEENS BOULEVARD", "extracted": [], "correct": ""}
{"text": "Come get a good massage on University Boulevard just a couple buildings south of Atlantic Boulevard $40 for 1/2 hour , $60 for 1 full hour Open 9a.m. to 11pm 7 days a week Call or text (904)802-7706 for an appointment or (walkins are welcome) 9-11 1832 University Boulevard South Jacksonville Florida 32216", "extracted": [], "correct": ""}
{"text": "CHINESE MASSAGE At MEI MEI - OPEN 10:00 AM - 10:00 PM with New Women Therapists for a 60 min - massage and Hot table shower for $60. 678-428-1906, available during normal business hours 10:00am - 10:00 pm, M-Sat: Sun 12 - 10pm. Phone for early or late appointments. From I-75, take Exit 259 to Cobb Pkwy , go north and we are behind the Lexus dealership on Cumberland Blvd., just 500 feet off of Cobb Pkwy . From 285, take the Cobb Pkwy . (Cumberland Mall) exit and follow Cobb Pkwy north to Cumberland Blvd. Look for our sign appx. 500 feet off Cobb Pkwy on Cumberland Blvd. Behind Starbucks and Docs Restaurant. 678-428-1906. Regular price is $40 for foot massage, and regular body massage for $60 for 60 min, $90/90 min, and $120/2-hrs. Table Shower normally $20 extra. This special offer can not be combined with any other offers or discounts. .", "extracted": [], "correct": ""}
{"text": "Incall LA MESA fletcher pkwy Outcall all SAN DIEGO I am EVERY man's DREAM Independent / Unrushed/FUN - 22", "extracted": [], "correct": ""}
{"text": "ENJOY A GREAT, PROFESSIONAL MASSAGE THERAPY SESSION 7 7 0 - 5 3 1 - 5 3 9 0 John W Morrow Jr Pkwy + Pearl Nix Pkwy .. [ N/E ]..OPEN Daily: 9am TO 9pm /", "extracted": [], "correct": ""}
{"text": "University pkwy incall Summer special:):):):) - 35", "extracted": [], "correct": ""}
{"text": "6817 SOUTHPOINT PARKWAY # 102 JACKSONVILLE FL 32216", "extracted": [], "correct": ""}
{"text": "Open 7 Days Weekly/ 10:00am-10:00pm Walk-ins Welcome Last Appointment Taken at 9:30pm (Shower Available) Address: 1422 28th Street Suite A, Sacramento CA, 95816 (Free Parking!!!) ? (916)457-2635 Deep Tissue/ Back Walking/ Swedish/ Sports Massage $40.00/30 mins $50.00/60 mins $75.00/90 mins $95.00/120 mins 1422 28th Street -Between N Street and O Street (Located in alley behind \"Ink Restaurant\" and in the same building as \"Relentless Tattoo\")", "extracted": [], "correct": ""}
{"text": "Looking for a sensual massage & naughty time?? Look no further, I love rubbing you all over and.. ;) ** Very Open Minded ** Fetishes Accepted ** Serious Inquiries Only Please!! ~~** TEXT **~~ 647-491-9918 *** Close to:*** Downtown Toronto, Yonge street , Bloor street , York street , Wellington street , Carelton street , Bay Street , College street , Yorkville, Gerrard, Dundas , Queen , King , Spadina , Bathurst", "extracted": [], "correct": ""}
{"text": "Clean Quite and Comfortable Private Rooms. Shower Available!!! Open 7 Days Weekly/ 10:00am-10:00pm Walk-ins Welcome Address: 1422 28th Street Suite A, Sacramento CA, 95816 ? (916)457-2635 Free Parking Deep Tissue/ Back Walking/ Swedish/ Sports Massage $40.00/30 mins $50.00/60 mins $75.00/90 mins $95.00/120 mins 1422 28th Street -Between N Street and O Street (Located in alley behind \"Ink Restaurant\" and in the same building as \"Relentless Tattoo\")", "extracted": [], "correct": ""}
{"text": "❀~❀~❀~WELCOME TO ASIAN BODY THERAPY CENTER ~❀~❀~❀ Clean Quite and Comfortable Private Rooms. Shower Available!!! Open 7 Days Weekly/ 10:00am-10:00pm Walk-ins Welcome Address: 1422 28th Street Suite A, Sacramento CA, 95816 Free Parking!!! Please Call Now For An Appointment! ☎ (916)457-2635(free parking) ~❀$40.00/30mins ~❀$50.00/60mins~❀$75.00/90mins~❀$95.00/120mins Deep Tissue/ Back Walking/ Swedish/ Sports Massage", "extracted": [], "correct": ""}
{"text": "Hola estoy disponible para darte un rico massage llmame 323 370 99 28 solo espaol Santa barbara, state street", "extracted": [], "correct": ""}
{"text": "open 7 days a week 9am - 9pm $70/hr $60/45 min Please call 413-262-0006 appointment only Free parking at street and across the street 78 maple street springfield downtown Ma 01105", "extracted": [], "correct": ""}
{"text": "Want the best tantric and sensual massage available in Liverpool Street or Old street ? Then let me tell you all about my exclusive body rub service! Hello boys! My names Cassandra Im a London-based, Canadian-sourced massage provider that knows how to provide the most relaxing and sensual massages Liverpool Street has to offer. Im sexy, smart, friendly and above all else, capable of putting a big smile on your face with my amazing hands! Liverpool Street is the thriving area Ive decided to call home and if youre able to come to my amazing flat just a few minutes away, youll find out just how accommodating and tantric I can be when sensual massages are required. Rest assured that I will do whatever it takes in order to ensure your complete satisfaction I also offer multiple types of massages for those that like a little variety when it comes to a great hands-on experience. Im also able to offer outcall services, although I prefer to invite guests over to mine as it makes it a lot easier for me to work my magic where I feel comfortable. My basic Liverpool Street sensual massages are available for just 120 per hour, but if you want body to body, mutual massaging or an authentic Nuru experience this can also be arranged. I should make it clear that when it comes to tantric massaging, I go all out to guarantee your pleasure. Just a few minutes with me will show you that Im capable of bringing a whole new meaning to the words tantric massage. I also have a few other girls available for massaging if you want to experience the variety that Liverpool Street has to offer! Head on over to my website and check out the My Sexy Friends page to see the gorgeous girls I work with. So what are you waiting for? Im right here and just cant wait to get my hands on you! Get in touch now and lets arrange a massage experience youll never forget. ;) I look forward to speaking to you soon! x For more information on my Liverpool Street erotic massages, check out my website: http://www.cassandrasmassage.co.uk/ You can also contact me on: Phone: 07479 218035 Email: contact@cassandrasmassage.co.uk", "extracted": [], "correct": ""}
{"text": "NORTH MAIN STREET SPA 1185 NORTH MAIN STREET PROVIDENCE, RI 02904 (401)-453-6677 9am-2am 7 DAYS A WEEK DRY & STEAM SAUNA ROOM FREE TABLE SHOWER (BODY SCRUB) RELAXING EROTIC & SENSUL FULL BODY RUBS $60/HOUR/CASH ONLY COME IN TO VISIT OUR SPA AND CHECK OUT OUR *** NEW *** AND *** FRIENDLY *** STAFF! ~~~~~~~~ COME TO RELAX ~~~~~~~~ ***** OPEN LATE UNTIL 2AM ***** 2 MINUTES AWAY FROM EXIT 25 OFF INTERSTATE 95 NORTH MAIN STREET SPA PROVIDE THE BEST RELAXING FULL BODY RUBS IN PROVIDENCE. THANKS! ALSO CHECK US OUT AT ***WWW.NORTHMAINSTREETSPA.NET*** FOR MORE INFO.", "extracted": [], "correct": ""}
{"text": "1185 NORTH MAIN STREET PROVIDENCE, RHODE ISLAND 02904 401-453-6677 9am-1am 7 DAYS A WEEK DRY STEAM SAUNA TABLE SHOWER (BODY SCRUB) EROTIC SENSUL FULL BODY RUBS $60/hr COME IN TO VISIT OUR SPA AND CHECK OUT OUR ***NEW*** AND ***FRIENDLY*** SIX GIRLS STAFF! NORTH MAIN STREET SPA PROVIDE THE BEST ASIAN RELAXING FULL BODY MASSAGE IN PROVIDENCE. THANKS!", "extracted": [], "correct": ""}
{"text": "We are looking for customers of High street banks to take part in some research for us. You will receive a fifty pounds incentive to Thank you for your time. The research will take an hour. If you are aged between 21 and 65 years old, and use a High Street bank then please email specifying the name of your Bank along with your contact number and we will call you straight back We are looking for people all over the UK so please feel free to pass this on to anyone else that might be interested I look forward to hearing from you", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}
{"text": "", "extracted": [], "correct": ""}