{"content":"Thank you Gainesville Gents. I made some new friends and enjoyed the Gator Nationals NHRA. Follow me on Twitter @ DiamondSquirt. Also, my website is listed on Twitter !","correct":{"twitter" : "DiamondSquirt"}}
{"content":"07761428935 Hey Guys, follow me on twitter and get some great offers updated weekly! @ESCORTLJ #LJGAYESCORT USE #LJCHEEKPIC on twitter to get discount! Sexuality: Gay Height: 5ft 9\" Weight: 63kg 9st13 139lb Build: Slim Penis size: Cut / Uncut: Uncut Feet size: 9 Eye colour: Brown Nationality: White British Calls: In Calls / Out Calls","correct":{"twitter" : "ESCORTLJ"}}
{"content":"Follow me on Twitter @shaunastylesgfe Hello gentlemen, My name is Shauna. I'm one of Colorado's most sought after Ebony providers. I'm highly reviewed on all local and national boards. If you desire the company of a beautiful, intelligent and sensual woman please visit my site to submit your booking request. Shaunastylesgfe.com Follow me on Twitter @shaunastylesGFE","correct":{"twitter" : "shaunastylesgfe"}}
{"content":"Hi I'm visiting new Orleans would like to get together. All my pics are real. I'm a 3x star.model. Call Me to hangout 5617275558. Follow me on twitter @desireemcggffee. Or email me. Cc OK!","correct":{"twitter":"desireemcggffee"}}
{"content":"29 years old (Forever) 5'3 (Short with Heels 5'6) Green Eyes (Changes Color With Mood) Long Blonde Hair (Run Fingers Through it) Great Curves (Real Woman) 36C Breasts (Handful) Soft Tanned Skin (Baby Soft To Touch) Come check out why I have rave reviews on all major sites. Outcall & incall willing to travel up to 50miles Kisses Katrina Kovell .katrinakovell.com (my site) 702-505-7800 *also follow on twitter @katrinakovell. See my other ads here","correct":{"twitter" : "katrinakovell"}}
{"content":"Hi Gentlemen. What a beautiful day. Come join me for some TRUE relaxation. I am located Southside, in adiscreeet incall locale. I stand at 5'3 ans weigh 120 lbs, measure 34DD-24-34. Brunette, Green Eyed and dark Tanned. I have more photos and info available on my website. You can find me on Twitter also. Twitter @MingStarrEnt. 780-953-6675. Me and my friends are on Adult Finder so you can find us all on there if you want... sticky_dolce","correct":{"twitter" : "MingStarrEnt"}}
{"content":"VIP PORTIA PAYNE. INCALLS EDMONTON SOUTHSIDE. OUTCALLS AT REQUEST TOO. MORE PHOTOS AVAILABLE TO YOU ON MY FACEBOOK & TWITTER @MINGSTARRENT. PLEASE CALL ME TO BOOK AN APPOINTMENT, 780-909-9709. I LOOK FORWARD TO HEARING FROM YOU :D WEBSITE CURRENTLY UN-AVAILABLE.. FB AND TWITTER ME. MWAH xoxo","correct":{"twitter" : "MINGSTARRENT"}}
{"content":"I am available for incalls at a clean, safe and discreet locale in Burnaby. Outcalls are also available to all major hotels and residences in the lower mainland. If booking with me it must be done via phone call, as I do not respond to text messages or emails. For more info please call me and make sure to follow me on Twitter @PortiaPaynee. 604-505-2443 TWITTER @PORTIAPAYNEE.","correct":{"twitter" : "PortiaPaynee"}}
{"content":"Hi I'm Desiree.Looking to hang out in New Orleans? U can come to me from 10am-2pm i will come to you from 3pm-12am. Cc's ok.let's make the big easy harder. ;-) Call me 5617275558.Email for a future date. Desiree1589@yahoo. Follow my twitter @desireemcggffee. Go on twitter to checkout my onlyfans/desireemcggffee site","correct":{"twitter" : "desireemcggffee"}}
{"content":"Bellisimas modelos reconocidas para altisimos empresarios y turistas twitter @chicasvipxxx","correct":{"twitter" :"chicasvipxxx"}}
{"content":"VIP celebrities MODELS 🌟🌟🌟🌟🌟 in Venezuela y miami, Extremely accommodating, exclusive for businessmen and tourists twitter @chicasvipxxx","correct":{"twitter" : "chicasvipxxx"}}
{"content":"Zarina, 100% REAL PHOTOS! 1h=2000aed, full night 6h=8000aed. ? Phone ? Whatsapp ? +7981-68-22-667 Nationality: Russian Age: 22yo Height: 168cm Weight: 48kg Hair: brown Eyes: green Measurements: 90-60-90cm Bust size: D (4) natural Speaking languages: English a little, Russian fluently Availability: In-call and Outcall from 9am till 3 am in Dubai. Extra services: sex with condom, OWC, foot fetish, massage ? Phone ? Whatsapp ? +7981-68-22-667 Luxe Dolls agency: Dubai escorts NEWS by twitter : https://twitter.com/EvaBiglova My facebook: https://www.facebook.com/eva.biglova.3 ? Dubai escort NEWS by Twitter ? Dubai escort NEWS by Facebook ? Phone ? Whatsapp ? +7981-68-22-667 ? Full list of the girls on our website: Dubai escorts","correct":{"twitter" : "EvaBiglova", "facebook": "eva.biglova.3", "Whatsapp" : "+7981-68-22-667"}}
{"content":"chica delgadita trigua de 18 aos buscala en parque lefevre cerca del push acropolis tarifa 50 la hora, horario hasta las 6pm whatsapp 66913387 twitter @consentidaspty","correct":{"whatsapp": "66913387", "twitter":"consentidaspty"}}
{"content":"Prepago independiente, la m��s fogosa y la m��s arrecha. Quieres el mejor sexo? ese te lo doy yo! Hola, soy Juanita, la prepago independiente m��s ardiente de Bogot��. Tengo unos senos de infarto, ��te imaginas tu verga en medio de mis grandes y fascinantes tetas? Si quieres disfrutar de una�� sensacional rusa y de todos mis servicios, solo tienes que llamarme o escribirme a mi whatsapp y seguirme en mis redes sociales.��Besitoos �� whatsapp : ��3228810090 twitter :����@Juanitaprepago �� Sensacional Prepago independiente, scort deliciosa solo en Bogot�� ��Hola, me llamo Juanita, la scort m��s rica y con las tetas m��s deliciosas de Bogot��, soy 100% fogosa. Ofrezo videollamada asi que escr��beme a mi whatsapp para acordar una cita ardiente y no olvides seguirme en mis redes sociales. �� whatsapp : ��3228810090 twitter :����@Juanitaprepago","correct":{"whatsapp" : "3228810090", "twitter" : "Juanitaprepago"}}
{"content":"Listo para una rusa? �� Hola soy Tatiana, tengo 18 a��itos soy una hermosa chica con unas tetas�� deliciosas y un cuerpo ideal para satisfacer tus m��s ardientes fantas��as, siempre dispuesta a consentirte, a tratarte mucho mejor que tu novia y a complacerte en todo lo que me pidas. s��gueme en mis redes sociales�� Facebook���� y ll��mame o escr��beme a whatsapp �� para agendar una cita.�� te aseguro que conmigo pasaras momentos sexualmmente increibles. ��Besitos ricos . whatsapp :�� 3203710148 twitter :����@Tatianavipcol facebook:���� www.facebook.com/tativipcol E-mail:�������� Tatiana@tatiana.in Sitio Web:�� http://www.tatianavip.com/ Hermosa prepago independiente Fogosa y complaciente Hola mi amor, soy Tatiana, una prepago independiente de 18 a��itos, te ofrezco mi compa����a y mis exclusivos�� y complacientes servicios sexuales. Te aseguro que voy a satisfacer todos tus deseos y peticiones, conmigo la vas a pasar delicioso! ll��mame o escr��beme a mi whatsapp y s��gueme en mis redes sociales. ��Un delicioso beso para ti whatsapp :�� 3203710148 twitter :����@Tatianavipcol facebook:���� www.facebook.com/tativipcol E-mail:�������� Tatiana@tatiana.in Sitio Web:�� http://www.tatianavip.com/ Hermos��sima prepago independiente,�� solo desea que toques el cielo de placer","correct":{"whatsapp" : "3203710148", "twitter" : "Tatianavipcol", "facebook":"www.facebook.com/tativipcol"}}
{"content":"Prepago independiente muy hermosa Hola soy Lorena, una prepago candente y súper complaciente, con muchas ganas de hacerte pasar momentos divinos y fuera de lo común, quieres tener tu verga dura dentro de mí?? Yo muero de ganas!! Escríbeme a mi WhatsApp y no olvides seguirme por twitter . Besotes! WhatsApp : 3202772977 Twitter : twitter.com/lorenaprepagocom E-mail: lorena@lorenavip.com","correct":{"whatsApp" : "3202772977", "twitter" : "lorenaprepagocom"}}
{"content":"💛 Only 100% Real of all ladies from the Luxe Dolls agency! Every time new girls!<br> 💛 Dating with sex and massage in elite 5 stars hotel on Lahore, Karachi, Islamabad area.<br> 💛 WhatsApp /Viber/Facetime/Call/sms +923214699343<br> 💛 WhatsApp /Viber/call/sms ++923214699343<br> 💛 My Twitter : Escorts Service Pakistan<br> 💛 If You see some New Pictures Please follow the links<br> 💛 <a rel=\"nofollow\" target=\"_blank\" href=\"https://t.co/4GIKC165IK\">https://t.co/4GIKC165IK</a><br> 💛 <a rel=\"nofollow\" target=\"_blank\" href=\"http://royalescorts.pk/\">http://royalescorts.pk/</a>","correct":{"whatsapp":"+923214699343"}}
{"content":"Laura, 100% REAL PHOTOS! 1h=2000aed, full night 6h=8000aed. ? Phone ? Whatsapp ? +7981-68-22-667 Laura, 100% REAL PHOTOS! 1h=2000aed, full night 6h=8000aed. ? Phone ? Whatsapp ? +7981-68-22-667 Nationality: Ukrainian Age: 27 years yang Height: 170 cm Weight: 57 kg Hair: blonde Eyes: blue Bust size: 3 (C) Speaking languages: English, Ukrainian Orientation: bi-sexual Services: Hot duo lesbian show with her friend Isabella. ? Phone ? Whatsapp ? +7981-68-22-667 ? Call ? 0079816822667 ? SMS/ whatsapp ? +79816822667 ? My Twitter : NEW Dubai escort ? My Facebook: hot Russian escorts ? Dubai gay ? Abu Dhabi escorts ? Muscat escorts ? Main website of Luxe Dolls: Dubai escort agency Only elite escorts, especially for nice gentlemen.","correct":{"whatsapp":"+7981-68-22-667"}}
{"content":"Hello... This is Nijuu... 27 years old... Athletic... English and japanese fluent... 5 feet 7 inches tall... Weight is 60 kilograms... Facebook, twitter , snapchat id is - Nijuuyonjikan ... Whatsapp , viber, mobile number is - +852 5189 6760","correct":{"facebook":"Nijuuyonjikan","twitter":"Nijuuyonjikan","snapchat":"Nijuuyonjikan","viber":"+852 5189 6760","whatsapp":"+852 5189 6760"}}
{"content":"Hello... This is Nijuu... I'm a japanese chinese filipina girl... Athletic... Independent... Discreet... Need to know more? Just ask :) Facebook account - Nijuu Yonjikan; Facebook page - Nijuuyonjikan; Twitter - Nijuuyonjikan; snapchat - Nijuuyonjikan; mobile number, whatsapp and viber is +852 5189 6760","correct":{"facebook":"Nijuuyonjikan","twitter":"Nijuuyonjikan","snapchat":"Nijuuyonjikan","viber":"+852 5189 6760","whatsapp":"+852 5189 6760"}}
{"content":"Face pix on request. Google Charley Cole to more of him, he's a porn model. We are housemates, can meet us as a duo or separatly. We can accom here in Manchester, and do outcalls anywhere. We are both experienced & professional escorts. Check out Max's Manchester Lads profile for reviews http://www.manchesterlads.com/Max-Sail.aspx + CAM SHOWS AVAILABLE + Max has private online vids to sell, ask for the list :) Whatsapp /Text - 07852170302 Kik - maxsail Twitter - @MaxSailXXX @charleycolexxx Snapchat - maxsailxxx","correct":{"snapchat":"maxsailxxx","twitter":["MaxSailXXX","charleycolexxx"],"whatsapp":"07852170302","kik":"maxsail"}}
{"content":"5'1 110pounds 32DD Visit TWITTER   Snapchat : keissyhennessey To verify I'm real William’s Lake : Fri 11 : 3pm-11pm Sat 12 : am 275/h or 325/h 180/hh or 220/hh www.KeissyHennessey.com Txt 514-974-9143","correct":{"snapchat":"keissyhennessey"}}
{"content":"Add me on facebook lexie rebekah an on snapchat Add me on Snapchat ! Add me on Snapchat ! Username: lkennedy306","correct":{"snapchat":"lkennedy306"}}
{"content":"Sexy young Irish girl looking for casual snapchat fun, release stress after my exams ;) snapchat me: janeewade","correct":{"snapchat":"janeewade"}}
{"content":"Looking to SNAPCHAT today. Only pics and videos. No meeting up. Pic for pic...video for video. My snapchat id is cancer1976","correct":{"snapchat":"cancer1976"}}
{"content":"21 female for snapchat shenanigans and fun. be cute, weird, quirky, sexy, silly, funny, etc. snapchat : aznsquishy","correct":{"snapchat":"aznsquishy"}}
{"content":"isabellavares - snapchat me ,i need dick","correct":{"snapchat":"isabellavares"}}
{"content":"New escort on the scene with a twist. 23 male available for whatever you desire. All welcome. Snapchat mvfscott to contact me. I'm Irish I work full time but behind closed doors I'm all yours. Hit me up Mvfscott","correct":{"snapchat":"mvfscott"}}
{"content":"NO BLACK MEN UNDER 35 T R I D : 316951 NOT A CATFISH google my # for R E V I E W S DONT ask dumb questions & NO PENNY PINCHERS . Generous GENTLEMEN ONLY. UPSCALE HOSTING. Cantonese & Black exotic barbie Unrushed & Polite. Always freshly showered & ready to play ALL GIFTS WRAPPED Call 8037435591 Follow me on Snapchat @qweenrenegade. See my menu of services on my profile BEFORE CALLING... EZSex","correct":{"snapchat":"qweenrenegade"}}
{"content":"2alieni Escort Boy, 34 anni - Imperia, Liguria, Italia Disponibile anche a: Savona Coppia ragazzi belli muscolosi e dotati Massaggio erotico a 4 mani Sesso attivo e passivo Snapchat : DUEalieni Sempre disponibili su whatsapp, snapchat o sms Per telefonate tutti i giorni dopo le 20:00 3425094171","correct":{"snapchat":"DUEalieni"}}
{"content":"Snapchat snapsexxxy I'll be back in a couple days - 20","correct":{"snapchat":"snapsexxxy"}}
{"content":"Very exotic open minded, Ready to play, please and pleasure. Hey guys, Let me Lilyanna be the maker of all your truly unforgettable memories.See why they call me Rain. Couple friendly & GFE Holiday Specials: Qv60 hhr120 Duos available w/Sophia Vee Trios Measurements: 36 DDD Medium panties 5'4 155 lbs Etiquette: NO low Balling OR Haggling NO AA men NO Vulgar conversation or all communication will be ended. ~**Lilyanna Rain**~ (360)843-9035 Follow on snapchat @LilyannaRain. See my menu of services on my profile BEFORE CALLING... EZSex Search for lips_where_uwant","correct":{"snapchat":"LilyannaRain"}}
{"content":"Name: Naomi Snapchat me: naomi4uxxx 25 Stats : 32DDD (enhanced) / 23 / 34 Height : 5' 5\" Weight : 120 lbs. Hair : Dark Brown Eyes : Green Ethnic : Caucasian Snapchat : Naomi4uxxx CALL or TEXT (587) 320-6336 TO BOOK. 250hr GF.E. I offer video/photo also, ask me on my profile before calling... EZSex","correct":{"snapchat":"Naomi4uxxx"}}
{"content":"27 curious lad snapchat danny1katelyn","correct":{"snapchat":"danny1katelyn"}}
{"content":"Hello, looking to satisfy the needs of respectable clients. add me on snapchat to book Snapchat : justheretoplay2","correct":{"snapchat":"justheretoplay2"}}
{"content":"������������ Amazing Mouth ���� Kimberly Rose (304) 323-8522 ������Looking for generous gentlemen only������ ������Tall Natural Blonde ������ ������Available Now������ ������Safe & Discreet������ ������No Drama, No Games, ������ I can come over to your place ���� ������������������������ (304) 323-8522 ������������ Amazing Mouth ���� 420friendly ���� Email Me: MissKimberlyRose304@gmail.com ���� ��������  snapchat me ���� KimberlyRose304","correct":{"snapchat":"KimberlyRose304"}}
{"content":"<br>💕💘🌟 Hello My Loves 🌟💘<br> 🍒 My name is Gigi 🍒<br> ⭐️ Snapchat : GigixKiss ⭐️ PROOF 100% 😏👅<br> Mexican & Argentina Godess 🌟👑 <br> 💞 5'1 / 34DDD size<br> Something NEW ✨😏 Freaky & Exciting 💕 is RIGHT here!<br> Call me Now 📞👅. 3232371609<br> 💖☎️ INCALLS ONLY<br> <br> I have V.I.P Hr SPECIALS 🌹EXTREME PLEASURES🍷✨ Ask Me 🌟💘 <br> ⭐️💋 Lets Take Our TiME Relax & Talk about all or DIRTY LittLe Secrets 🌟💘<br> 💘💕 I will have U Coming Back For More 💖💋 <br> 🌹 3232371609 🌹 <br> ❌ NO BLACK MEN❌ NO PRIVATE NUMBERS","correct":{"snapchat":"GigixKiss"}}
{"content":"Hello My Loves My name is Gigi Snapchat : GigixKiss PROOF 100% Mexican & Argentina Godess 5'1 / 34DDD size Something NEW Freaky & Exciting is RIGHT here. Call Me . (213)2979401 INCALLS ONLY I have V.I.P Hr SPECIALS EXTREME PLEASURES Ask Me Lets Take Our TiME Relax & Talk about all or DIRTY LittLe Secrets I will have U Coming Back For More CALL Me:(213)2979401 NO BLACK MEN NO PRIVATE NUMBERS","correct":{"snapchat":"GigixKiss"}}
{"content":"Hi Im Diamond 100% Real verify me via Twitter/ Instagram @DiamondMonrow. Im offering full body to body Nuru massages. My services is to help you reach your ultimate relaxation. I enjoy what I do and relish showing my nice and my naughty side. You will not be disappointed. Outcall to your hotel or home Cab fair may be added , Incall Is also an option . 150 HALF HR/ 200HR/ 300 Deluxe Give me a call (208)450-2350","correct":{"instagram":"DiamondMonrow","Twitter":"DiamondMonrow"}}
{"content":"Hello ���� my name is Daisy ���� . If your looking ���� for a young ���� Beautiful ��� & open minded ���� Latina ���� Look no further ���� I'm your girl ������ Feel free to call or text me ���� Any time ������ 510-938-8747 ������� Snapchat @ beautifuladri18 ���� Instagram @ you.neek ���� ���� P A S A D E N D A ����","correct":{"instagram":"you.neek","snapchat":"beautifuladri18"}}
{"content":"Listen gents you already know. You can follow me on Instagram @BUGATTICREAM. Or better yet give me a call ? Bugatti Cream ? ? 929 232 9093. See you soon ?","correct":{"instagram":"BUGATTICREAM"}}
{"content":"Come every Thursday 10937 Burbank Blvd. North Hollywood Hostesses Ts Athletic Body and Audry Cobra welcome you to meet the girls! Door opens at 10. Show at 12. Close at 2. 10 cover Check out the new instagram : transfixla","correct":{"instagram":"transfixla"}}
{"content":"Wechat : TosiEscorts Wechat : TosiEscorts Wechat : TosiEscorts Wechat : TosiEscorts If you desire an unforgettable experience that is hot, sexy and simply 100% real? Stop wasting your time...WE ARE right here for you!!! call me, We are waiting. If Exotic and Erotic is what your looking for, then We are the girls for you!! Wechat us and Un rushed sessions!! OUTCALL ONLY!!","correct":{"wechat":"TosiEscorts"}}
{"content":"???????? ???? ???? ???? ???? ???? ??? wechat id: hotlaxgirl ?????","correct":{"wechat":"hotlaxgirl"}}
{"content":"Hi ;) I came back with some more reviews tonight. The Most recent ones. I have over 30+ reviews on my wechat moment so please come and check me on :3 I believe I'm already very famous among backpage users, and I'm really glad that many people give me so much credit for the hot and passionate night we enjoyed together! But You are the ones who made my day with your respectful and gentle night! I would like to thank everyone who came to find my service!!!!!!!! For Those who don't know me: I'm Mihye the Wechat girl, the original of wechat -only-advertisements and the only one with real reviews from clients! I am legit and real _ I heard that I come highly recommended by the \"King of Backpage\", but I don't know who you are, and you say that you are one of my regulars!! Please send me a wechat to let me know! I really wanna know who King is :---) Anyways! Guys who want to have so much fun with me tonight should Send me a wechat to: ️❤️❤️ Wechat id : Gva16r️❤️❤️ ❤️❤️ Wechat id : Gva16r️❤️❤️ ❤️❤️ Wechat id : Gva16r️❤️❤️ ❤️❤️ Wechat id : Gva16r️❤️❤️","correct":{"wechat":"Gva16r"}}
{"content":"Hello! It's Mihye here! :3 PLEASE READ THE ADVERTISEMENT CAREFULLY! I have been in backpage for 2 months now! I am so so so so so grateful for everyone who has contacted me and actually reached out to meet up!!!! Thanks for everyone for support and hearty reviews.....;) Mihye will try harder to catch your attention and to provide good service and unforgettable nights ! ♥♥♥ Kind reminder: I am the original of the wechat series that are everywhere now in Backpage and I'm the only one with REVIEW system with multiple clients:) I posted some of my reviews on my ad, please add me on Wechat for more information ABOUT WECHAT : Wechat is a free app from China that has cute emojis and simple system! It is completely free in terms of your personal information (you can use email) and IF you don't have it, PLEASE install it from Either Appstore or Android Market! It's a FREE APP! like Whatsapp or Kakao - but only better because u dont need to put your phone number! So please add me on::::: wechat ♥ gva16r ♥ wechat ♥ gva16r ♥ Thanks for reading my advertisement.. ♥ I've seen so many people with a big smile when I come in to their rooms and after we are done enjoying _ Can I see your smile tonight.... ♥ wechat ♥ gva16r ♥ wechat ♥ gva16r ♥","correct":{"wechat":"gva16r"}}
{"content":"Hi~! 9 Clients have satisfied themselves with me~ I'm Wechat girl Mihye _ I dont do email only wechat because I know we need immediate response :-) Rate 260,000KRW Service: Massage, French Kiss, BBBJ and SEX No bareback sex is allowed. Wechat to: GVA16R","correct":{"wechat":"GVA16R"}}
{"content":"Hello, im looking for bdsm and mistress shemale. Im 21 years old Please contact me on wechat ID:wewo94","correct":{"wechat":"wewo94"}}
{"content":"Hello! are you tired of waiting for an email? Here's Me! We can have immediate response~~ 260000KRW / Hour rate Service and Details, add me on wechat GVA16R","correct":{"wechat":"GVA16R"}}
{"content":"New York Asian Escort www.nyasianangels.com text: 585-466-0383 Wechat : aa5854660383 Asian Angel 20, 5'7, 34c, 105 lbs Asian Car Model, super sexy, slim, tall, first time in New York Incall: Flushing hotel outcall: Anywhere New York text: 585-466-0383 Wechat : aa5854660383 (register innercircle to get recent photo)","correct":{"wechat":"aa5854660383"}}