{"text": "Thank you Gainesville Gents. I made some new friends and enjoyed the Gator Nationals NHRA. Follow me on Twitter @ DiamondSquirt. Also, my website is listed on Twitter !", "correct": {"twitter": ["DiamondSquirt"]}}
{"text": "Follow me on Twitter @shaunastylesgfe Hello gentlemen, My name is Shauna. I'm one of Colorado's most sought after Ebony providers. I'm highly reviewed on all local and national boards. If you desire the company of a beautiful, intelligent and sensual woman please visit my site to submit your booking request. Shaunastylesgfe.com Follow me on Twitter @shaunastylesGFE", "correct": {"twitter": ["shaunastylesgfe"]}}
{"text": "Hi I'm visiting new Orleans would like to get together. All my pics are real. I'm a 3x star.model. Call Me to hangout 5617275558. Follow me on twitter @desireemcggffee. Or email me. Cc OK!", "correct": {"twitter": ["desireemcggffee"]}}
{"text": "29 years old (Forever) 5'3 (Short with Heels 5'6) Green Eyes (Changes Color With Mood) Long Blonde Hair (Run Fingers Through it) Great Curves (Real Woman) 36C Breasts (Handful) Soft Tanned Skin (Baby Soft To Touch) Come check out why I have rave reviews on all major sites. Outcall & incall willing to travel up to 50miles Kisses Katrina Kovell .katrinakovell.com (my site) 702-505-7800 *also follow on twitter @katrinakovell. See my other ads here", "correct": {"twitter": ["katrinakovell"]}}
{"text": "Hi Gentlemen. What a beautiful day. Come join me for some TRUE relaxation. I am located Southside, in adiscreeet incall locale. I stand at 5'3 ans weigh 120 lbs, measure 34DD-24-34. Brunette, Green Eyed and dark Tanned. I have more photos and info available on my website. You can find me on Twitter also. Twitter @MingStarrEnt. 780-953-6675. Me and my friends are on Adult Finder so you can find us all on there if you want... sticky_dolce", "correct": {"twitter": ["MingStarrEnt"]}}
{"text": "VIP PORTIA PAYNE. INCALLS EDMONTON SOUTHSIDE. OUTCALLS AT REQUEST TOO. MORE PHOTOS AVAILABLE TO YOU ON MY FACEBOOK & TWITTER @MINGSTARRENT. PLEASE CALL ME TO BOOK AN APPOINTMENT, 780-909-9709. I LOOK FORWARD TO HEARING FROM YOU :D WEBSITE CURRENTLY UN-AVAILABLE.. FB AND TWITTER ME. MWAH xoxo", "correct": {"twitter": ["MINGSTARRENT"]}}
{"text": "I am available for incalls at a clean, safe and discreet locale in Burnaby. Outcalls are also available to all major hotels and residences in the lower mainland. If booking with me it must be done via phone call, as I do not respond to text messages or emails. For more info please call me and make sure to follow me on Twitter @PortiaPaynee. 604-505-2443 TWITTER @PORTIAPAYNEE.", "correct": {"twitter": ["PortiaPaynee"]}}
{"text": "Hi I'm Desiree.Looking to hang out in New Orleans? U can come to me from 10am-2pm i will come to you from 3pm-12am. Cc's ok.let's make the big easy harder. ;-) Call me 5617275558.Email for a future date. Desiree1589@yahoo. Follow my twitter @desireemcggffee. Go on twitter to checkout my onlyfans/desireemcggffee site", "correct": {"twitter": ["desireemcggffee"]}}
{"text": "VIP celebrities MODELS \ud83c\udf1f\ud83c\udf1f\ud83c\udf1f\ud83c\udf1f\ud83c\udf1f in Venezuela y miami, Extremely accommodating, exclusive for businessmen and tourists twitter @chicasvipxxx", "correct": {"twitter": ["chicasvipxxx"]}}
{"text": "Hello... This is Nijuu... I'm a japanese chinese filipina girl... Athletic... Independent... Discreet... Need to know more? Just ask :) Facebook account - Nijuu Yonjikan; Facebook page - Nijuuyonjikan; Twitter - Nijuuyonjikan; snapchat - Nijuuyonjikan; mobile number, whatsapp and viber is +852 5189 6760", "correct": {"twitter": ["Nijuuyonjikan"], "snapchat": ["Nijuuyonjikan"]}}
{"text": "Face pix on request. Google Charley Cole to more of him, he's a porn model. We are housemates, can meet us as a duo or separatly. We can accom here in Manchester, and do outcalls anywhere. We are both experienced & professional escorts. Check out Max's Manchester Lads profile for reviews http://www.manchesterlads.com/Max-Sail.aspx + CAM SHOWS AVAILABLE + Max has private online vids to sell, ask for the list :) Whatsapp /Text - 07852170302 Kik - maxsail Twitter - @MaxSailXXX @charleycolexxx Snapchat - maxsailxxx", "correct": {"twitter": ["MaxSailXXX"], "snapchat": ["maxsailxxx"]}}
{"text": "5'1 110pounds 32DD Visit TWITTER   Snapchat : keissyhennessey To verify I'm real William\u2019s Lake : Fri 11 : 3pm-11pm Sat 12 : am 275/h or 325/h 180/hh or 220/hh www.KeissyHennessey.com Txt 514-974-9143", "correct": {"snapchat": ["keissyhennessey"]}}
{"text": "Sexy young Irish girl looking for casual snapchat fun, release stress after my exams ;) snapchat me: janeewade", "correct": {"snapchat": ["janeewade"]}}
{"text": "Looking to SNAPCHAT today. Only pics and videos. No meeting up. Pic for pic...video for video. My snapchat id is cancer1976", "correct": {"snapchat": ["cancer1976"]}}
{"text": "21 female for snapchat shenanigans and fun. be cute, weird, quirky, sexy, silly, funny, etc. snapchat : aznsquishy", "correct": {"snapchat": ["aznsquishy"]}}
{"text": "New escort on the scene with a twist. 23 male available for whatever you desire. All welcome. Snapchat mvfscott to contact me. I'm Irish I work full time but behind closed doors I'm all yours. Hit me up Mvfscott", "correct": {"snapchat": ["mvfscott"]}}
{"text": "NO BLACK MEN UNDER 35 T R I D : 316951 NOT A CATFISH google my # for R E V I E W S DONT ask dumb questions & NO PENNY PINCHERS . Generous GENTLEMEN ONLY. UPSCALE HOSTING. Cantonese & Black exotic barbie Unrushed & Polite. Always freshly showered & ready to play ALL GIFTS WRAPPED Call 8037435591 Follow me on Snapchat @qweenrenegade. See my menu of services on my profile BEFORE CALLING... EZSex", "correct": {"snapchat": ["qweenrenegade"]}}
{"text": "2alieni Escort Boy, 34 anni - Imperia, Liguria, Italia Disponibile anche a: Savona Coppia ragazzi belli muscolosi e dotati Massaggio erotico a 4 mani Sesso attivo e passivo Snapchat : DUEalieni Sempre disponibili su whatsapp, snapchat o sms Per telefonate tutti i giorni dopo le 20:00 3425094171", "correct": {"snapchat": ["DUEalieni"]}}
{"text": "Very exotic open minded, Ready to play, please and pleasure. Hey guys, Let me Lilyanna be the maker of all your truly unforgettable memories.See why they call me Rain. Couple friendly & GFE Holiday Specials: Qv60 hhr120 Duos available w/Sophia Vee Trios Measurements: 36 DDD Medium panties 5'4 155 lbs Etiquette: NO low Balling OR Haggling NO AA men NO Vulgar conversation or all communication will be ended. ~**Lilyanna Rain**~ (360)843-9035 Follow on snapchat @LilyannaRain. See my menu of services on my profile BEFORE CALLING... EZSex Search for lips_where_uwant", "correct": {"snapchat": ["LilyannaRain"]}}
{"text": "Name: Naomi Snapchat me: naomi4uxxx 25 Stats : 32DDD (enhanced) / 23 / 34 Height : 5' 5\" Weight : 120 lbs. Hair : Dark Brown Eyes : Green Ethnic : Caucasian Snapchat : Naomi4uxxx CALL or TEXT (587) 320-6336 TO BOOK. 250hr GF.E. I offer video/photo also, ask me on my profile before calling... EZSex", "correct": {"snapchat": ["Naomi4uxxx"]}}
{"text": "Hello, looking to satisfy the needs of respectable clients. add me on snapchat to book Snapchat : justheretoplay2", "correct": {"snapchat": ["justheretoplay2"]}}
{"text": "<br>\ud83d\udc95\ud83d\udc98\ud83c\udf1f Hello My Loves \ud83c\udf1f\ud83d\udc98<br> \ud83c\udf52 My name is Gigi \ud83c\udf52<br> \u2b50\ufe0f Snapchat : GigixKiss \u2b50\ufe0f PROOF 100% \ud83d\ude0f\ud83d\udc45<br> Mexican & Argentina Godess \ud83c\udf1f\ud83d\udc51 <br> \ud83d\udc9e 5'1 / 34DDD size<br> Something NEW \u2728\ud83d\ude0f Freaky & Exciting \ud83d\udc95 is RIGHT here!<br> Call me Now \ud83d\udcde\ud83d\udc45. 3232371609<br> \ud83d\udc96\u260e\ufe0f INCALLS ONLY<br> <br> I have V.I.P Hr SPECIALS \ud83c\udf39EXTREME PLEASURES\ud83c\udf77\u2728 Ask Me \ud83c\udf1f\ud83d\udc98 <br> \u2b50\ufe0f\ud83d\udc8b Lets Take Our TiME Relax & Talk about all or DIRTY LittLe Secrets \ud83c\udf1f\ud83d\udc98<br> \ud83d\udc98\ud83d\udc95 I will have U Coming Back For More \ud83d\udc96\ud83d\udc8b <br> \ud83c\udf39 3232371609 \ud83c\udf39 <br> \u274c NO BLACK MEN\u274c NO PRIVATE NUMBERS", "correct": {"snapchat": ["GigixKiss"]}}
{"text": "Hello My Loves My name is Gigi Snapchat : GigixKiss PROOF 100% Mexican & Argentina Godess 5'1 / 34DDD size Something NEW Freaky & Exciting is RIGHT here. Call Me . (213)2979401 INCALLS ONLY I have V.I.P Hr SPECIALS EXTREME PLEASURES Ask Me Lets Take Our TiME Relax & Talk about all or DIRTY LittLe Secrets I will have U Coming Back For More CALL Me:(213)2979401 NO BLACK MEN NO PRIVATE NUMBERS", "correct": {"snapchat": ["GigixKiss"]}}
{"text": "Hi Im Diamond 100% Real verify me via Twitter/ Instagram @DiamondMonrow. Im offering full body to body Nuru massages. My services is to help you reach your ultimate relaxation. I enjoy what I do and relish showing my nice and my naughty side. You will not be disappointed. Outcall to your hotel or home Cab fair may be added , Incall Is also an option . 150 HALF HR/ 200HR/ 300 Deluxe Give me a call (208)450-2350", "correct": {"instagram": ["DiamondMonrow"]}}
{"text": "Listen gents you already know. You can follow me on Instagram @BUGATTICREAM. Or better yet give me a call ? Bugatti Cream ? ? 929 232 9093. See you soon ?", "correct": {"instagram": ["BUGATTICREAM"]}}
{"text": "Come every Thursday 10937 Burbank Blvd. North Hollywood Hostesses Ts Athletic Body and Audry Cobra welcome you to meet the girls! Door opens at 10. Show at 12. Close at 2. 10 cover Check out the new instagram : transfixla", "correct": {"instagram": ["transfixla"]}}
{"text": "Wechat : TosiEscorts Wechat : TosiEscorts Wechat : TosiEscorts Wechat : TosiEscorts If you desire an unforgettable experience that is hot, sexy and simply 100% real? Stop wasting your time...WE ARE right here for you!!! call me, We are waiting. If Exotic and Erotic is what your looking for, then We are the girls for you!! Wechat us and Un rushed sessions!! OUTCALL ONLY!!", "correct": {"wechat": ["TosiEscorts"]}}
{"text": "???????? ???? ???? ???? ???? ???? ??? wechat id: hotlaxgirl ?????", "correct": {"wechat": ["hotlaxgirl"]}}
{"text": "Hello, im looking for bdsm and mistress shemale. Im 21 years old Please contact me on wechat ID:wewo94", "correct": {"wechat": ["wewo94"]}}
{"text": "Hello! are you tired of waiting for an email? Here's Me! We can have immediate response~~ 260000KRW / Hour rate Service and Details, add me on wechat GVA16R", "correct": {"wechat": ["GVA16R"]}}
{"text": "New York Asian Escort www.nyasianangels.com text: 585-466-0383 Wechat : aa5854660383 Asian Angel 20, 5'7, 34c, 105 lbs Asian Car Model, super sexy, slim, tall, first time in New York Incall: Flushing hotel outcall: Anywhere New York text: 585-466-0383 Wechat : aa5854660383 (register innercircle to get recent photo)", "correct": {"wechat": ["aa5854660383"]}}
{"text": "", "correct":{}}